### ISSUE TITLE
Add Async suffix to the async methods.

### ISSUE THREAD

**Issue by sonnemaf** [SimonCropp/Replicant#2]
I think that the async methods String(), Bytes(), ToFile() and ToStream() must have a Async suffix in the method name. This makes them easier to discover that they are async and should be awaited. See the Microsoft [guidelines](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model#:~:text=The%20name%20of%20an%20async,return%20statement%20with%20no%20operand.)

# Current
```
var content = await httpCache.String("https://httpbin.org/json");
await httpCache.ToFile("https://httpbin.org/json", targetFile);
```

# Expected
```
var content = await httpCache.GetStringAsync("https://httpbin.org/json");
await httpCache.ToFileAsync("https://httpbin.org/json", targetFile);
```

**Comment by SimonCropp** [comment]
can u try 0.1.0-beta.9
